[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Edit", for = "unix" }
]

[open]
rules = [
    # If it's a text file, use the 'edit' opener defined above
    { mime = "text/*", use = "edit" },
    { mime = "application/json", use = "edit" },
    { name = "*.py", use = "edit" },
    { name = "*.js", use = "edit" },
    { name = "*.jsx", use = "edit" },
    { name = "*.css", use = "edit" },
    { name = "*.html", use = "edit" },
    { name = "*.md", use = "edit" },
]
